### ISSUE TITLE
newbie for sunxi soc...Can you kindly tell me which chip can this code run on?

### ISSUE THREAD

**Issue by 9crk** [rellla/libvdpau-sunxi#5]
I'm working on Allwinner H3 hardware  decode and display function.
I got no resource to achive my goal...will this work on my nanoPi M1 board?

**Comment by rellla** [comment]
This branch - the default "staging" - only works with A10 and A20. So no H3 / NanoPi M1.
You have to use the upstream branch https://github.com/linux-sunxi/libvdpau-sunxi for H3.
Regards

**Comment by 9crk** [comment]
I noticed that it contains three branch. libcsptr/master/staging  , there is no such branch named "upstream", which branch can i use?

**Comment by 9crk** [comment]
I see it ..https://github.com/rellla/libvdpau-sunxi/tree/upstream   in your code.not in the official sunxi's repo.

**Comment by rellla** [comment]
With "upstream" i meant the default master branch.
If you want to make experiments, you can also try the libcsptr branch. All branches in my private repository are highly experimental, so be aware :)
To see the connections between all the branches, please see https://github.com/linux-sunxi/libvdpau-sunxi/network and read the commit logs. There you will find something about "H3".... In some branches...
Regards

**Comment by 9crk** [comment]
would you mind a few question...where are you? are you Chinese? are you an employee of AllwinnerTech? where did you get all those resources? 

you hlept me alot.. now I'm going to run the master branch on lichee..god bless me :dancers: 

Thanks one more time...

**Comment by rellla** [comment]
no chinese. no allwinner. go reading www.linux-sunxi.org and you get an overview of who all the people are that do the work, which allwinner is going not to do.
i suppose you use some allwinner kernel or image, because you write about lichee......
drop that and use the software, linux-sunxi community works on. you will have more fun in the end.

**Comment by 9crk** [comment]
you mean linux-sunxi.org is none of AllwinnerTech's business?

btw. if I use this https://github.com/linux-sunxi/linux-sunxi  for kernel, then which branch should I use?

is there any document about choosing the branch of a certain chip ?

——————I got it..http://linux-sunxi.org/Linux

**Comment by rellla** [comment]
linux-sunxi.org has NOTHING to do with Allwinner. Allwinner is neither helping nor contributing in all this effort.
First rule: When wanting do deal with all this development thing, go first reading the wiki. It's all there.
Go to the chip's page and see what it is saying about linux-sunxi (legacy) kernel or mainline kernel support. This will indeed take a few minutes....
rellla
